spring:
  datasource:
    url: jdbc:mysql://localhost:3306/108pq?useSSL=false&serverTimezone=UTC
    username: root
    password: z123456
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml

